name: Release NuGet packages on release created

on:
  release:
    types: [created]

jobs:
  get-version:
    name: Get version from tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract version from tag
        id: get-version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\/v/}"

  release-nuget-packages:
    name: Release NuGet packages
    runs-on: ubuntu-latest
    needs: [get-version]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Set VERSION variable
        run: echo "VERSION=${{ needs.get-version.outputs.version }}" >> $GITHUB_ENV
      - name: Set MSBUILD_PROPERTIES variable
        run: echo "MSBUILD_PROPERTIES=/p:Version=${VERSION} /p:RepositoryUrl=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} /p:PublishRepositoryUrl=true" >> $GITHUB_ENV
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build /p:Version=${VERSION} ${MSBUILD_PROPERTIES} --configuration Release --no-restore
      - name: Test
        run: dotnet test /p:Version=${VERSION} ${MSBUILD_PROPERTIES} --configuration Release --no-restore --no-build --verbosity normal
      - name: Pack
        run: dotnet pack /p:Version=${VERSION} ${MSBUILD_PROPERTIES} --configuration Release --no-restore --no-build --include-source --include-symbols --output . 
      - name: Push
        run: |
          dotnet nuget push DotnetNlp.RuleEngine.Core.${VERSION}.nupkg --source ${SERVER_URL} --api-key ${GITHUB_TOKEN}
          dotnet nuget push DotnetNlp.RuleEngine.Mechanics.Peg.${VERSION}.nupkg --source ${SERVER_URL} --api-key ${GITHUB_TOKEN}
          dotnet nuget push DotnetNlp.RuleEngine.Mechanics.Regex.${VERSION}.nupkg --source ${SERVER_URL} --api-key ${GITHUB_TOKEN}
          dotnet nuget push DotnetNlp.RuleEngine.Bundle.${VERSION}.nupkg --source ${SERVER_URL} --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

  release-pypi-packages:
    name: Release PyPI packages
    runs-on: ubuntu-latest
    needs: [get-version]
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: dotnet-nlp/rule-engine-python
          event-type: release-pypi-packages
          client-payload: '{"ref": "${{ github.ref }}", "version": "${{ needs.get-version.outputs.version }}"}'