name: Release NuGet packages on version tag created
on:
  create:
    tags:
      - v*
jobs:
  release-nuget-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - uses: actions/setup-dotnet@v2
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test --no-build --configuration Release /p:Version=${VERSION} --verbosity normal
      - name: Pack
        run: dotnet pack --no-build --configuration Release /p:Version=${VERSION} --output .
      - name: Push
        run: |
          dotnet nuget push RuleEngine.Core.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push RuleEngine.Mechanics.Peg.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push RuleEngine.Mechanics.Regex.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

